version: "3.2"

services:
  db:
    image: mysql:8.0
    container_name: mysql_ssra
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jasmin

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ssra
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
